# Generated by Django 4.2.19 on 2025-02-17 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0002_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_cliente',
            new_name='id_Cliente',
        ),
        migrations.CreateModel(
            name='ItenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=20)),
                ('preco_unitario', models.CharField(max_length=20)),
                ('id_Pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_pedidos.pedido')),
            ],
        ),
    ]
