# Generated by Django 4.2.19 on 2025-02-18 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pedidos', '0003_rename_id_cliente_pedido_id_cliente_itenpedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItenPedido',
            new_name='ItemPedido',
        ),
    ]
